import { defineConfig } from "vite";

export default defineConfig({
  base: '/',
  build: {
    assetsInclude: [
      "**/*.jpeg",
      "**/*.jpg",
      "**/*.png",
      "**/*.svg",
      "**/*.gif",
      "**/*.webp",
      "**/*.avif",
      "**/*.ico",
      "**/*.woff",
      "**/*.woff2",
      "**/*.ttf",
      "**/*.eot",
      "**/*.otf",
      "**/*.svg",
      "**/*.webp",
      "**/*.avif",
      "**/*.ico",
      "**/*.woff",
      "**/*.woff2",
      "**/*.ttf",
      "**/*.eot",
      "**/*.otf",
      "**/*.svg",
      "**/*.webp",
      "**/*.avif",
      "**/*.ico",
      "**/*.woff",
      "**/*.woff2",
      "**/*.ttf",
      "**/*.eot",
      "**/*.otf",
      "**/*.svg",
      "**/*.webp",
      "**/*.avif",
      "**/*.ico",
      "**/*.woff",
      "**/*.woff2",
      "**/*.ttf",
      "**/*.eot",
      "**/*.otf",
      "**/*.svg",
      "**/*.webp",
      "**/*.avif",
      "**/*.ico",
      "**/*.woff",
      "**/*.woff2",
      "**/*.ttf",
      "**/*.eot",
      "**/*.otf",
      "**/*.svg",
      "**/*.webp",
      "**/*.avif",
      "**/*.ico",
      "**/*.woff",
      "**/*.woff2",
      "**/*.ttf",
      "**/*.eot",
      "**/*.otf",
      "**/*.svg",
    ],
    outDir: 'dist',

    copyPublicDir: true,

    rollupOptions: {
      output: {
        assetFileNames: "assets/[name].[ext]",
      },
    },
  },
});
